inherits = "kanagawa"

"ui.statusline.normal" = { fg = "sumiInk0", bg = "waveRed", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { fg = "sumiInk0", bg = "springBlue", modifiers = [
  "bold",
] }
"ui.statusline.select" = { fg = "sumiInk0", bg = "lotusGreen", modifiers = [
  "bold",
] }

"keyword" = { fg = "oniViolet" }

[palette]
lotusGreen = "#6f894e"
