context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "AG08_Mic"
            capture.props = {
                node.name = "capture.AG08_Mic"
                audio.position = [ AUX0 AUX1 ]
                stream.dont-remix = true
                target.object = "alsa_input.usb-Yamaha_Corporation_Yamaha_AG08-00.multichannel-input"
                node.passive = true
            }
            playback.props = {
                node.name = "AG08_Mic"
                media.class = "Audio/Source"
                audio.position = [ STEREO ]
            }
        }
    }
]
