context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "AG08_Stereo"
            capture.props = {
                node.name = "AG08_Stereo"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.name = "playback.AG08_Stereo"
                audio.position = [ AUX2 AUX3 ]
                target.object = "alsa_card.usb-Yamaha_Corporation_Yamaha_AG08-00"
                stream.dont-remix = true
                node.passive = true
            }
        }
    }
]
