format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$custom\
$cmd_duration\
$character"""

add_newline = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[nodejs]
style = "bold green"

[custom.jj]
command = '''
jj log -r@ -l1 --ignore-working-copy --no-graph --color always  -T '
  separate("",
    coalesce(
      if(hidden, "hidden"),
      if(divergent, "divergent"),
      if(conflict, "conflict"),
      branches.map(|x| if(
          x.name().substr(0, 10).starts_with(x.name()),
          x.name().substr(0, 10),
          x.name().substr(0, 9) ++ "…")
        ).join(" "),
      tags.map(|x| if(
          x.name().substr(0, 10).starts_with(x.name()),
          x.name().substr(0, 10),
          x.name().substr(0, 9) ++ "…")
        ).join(" ")
    ),
    surround("@", "", self.change_id().shortest())
  )
'
'''
detect_folders = [".jj"]
symbol = "󰝴 "
style = "bold blue"
