# Inserts a blank line between shell prompts
add_newline = true

[line_break]
disabled = true

[character]                            
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)" 

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[rust]
symbol = "🦀 "

[nodejs]
style = "bold green"
