# Shell variables
# Generated by 'wal'
wallpaper='/home/karei/Pictures/wave1.jpg'

# Special
background='#0d0615'
foreground='#f4c1c0'
cursor='#f4c1c0'

# Colors
color0='#0d0615'
color1='#DF3655'
color2='#9F576F'
color3='#A76D7C'
color4='#ED5761'
color5='#9D668B'
color6='#E86D8A'
color7='#f4c1c0'
color8='#aa8786'
color9='#DF3655'
color10='#9F576F'
color11='#A76D7C'
color12='#ED5761'
color13='#9D668B'
color14='#E86D8A'
color15='#f4c1c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
