return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "diff",
      "html",
      "lua",
      "luadoc",
      "rust",
      "toml",
      "vim",
      "vimdoc",
      "yaml",
      "zig",
    },
    auto_install = false,
    highlight = { enable = true, disable = { "markdown" } },
    indent = { enable = true },
  },
}
