[user]
name = "karei"
email = "mail@karei.dev"

[ui]
default-command = "status"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[aliases]
b = ["bookmark"]
bm = ["bookmark", "move"]
bu = ["bookmark", "move", "--to", "@-"]

[signing]
sign-all = true
backend = "gpg"

[template-aliases]
'format_short_signature(signature)' = 'signature'
