[user]
name = "karei"
email = "mail@karei.dev"

[ui]
default-command = "status"

[signing]
key = ""
sign-all = true
backend = "gpg"

[template-aliases]
'format_short_signature(signature)' = 'signature'
